/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class IndoorPositionMeasurement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IndoorPositionMeasurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndoorPositionMeasurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_IndoorPositionMeasurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResult(double[] value) {
    IPSJNI.IndoorPositionMeasurement_result_set(swigCPtr, this, value);
  }

  public double[] getResult() {
    return IPSJNI.IndoorPositionMeasurement_result_get(swigCPtr, this);
  }

  public void setLocatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_locatestate_set(swigCPtr, this, value);
  }

  public int getLocatestate() {
    return IPSJNI.IndoorPositionMeasurement_locatestate_get(swigCPtr, this);
  }

  public void setL5_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_L5_result_set(swigCPtr, this, value);
  }

  public double[] getL5_result() {
    return IPSJNI.IndoorPositionMeasurement_L5_result_get(swigCPtr, this);
  }

  public void setL5_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_L5_locatestate_set(swigCPtr, this, value);
  }

  public int getL5_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_L5_locatestate_get(swigCPtr, this);
  }

  public void setL1_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_L1_result_set(swigCPtr, this, value);
  }

  public double[] getL1_result() {
    return IPSJNI.IndoorPositionMeasurement_L1_result_get(swigCPtr, this);
  }

  public void setL1_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_L1_locatestate_set(swigCPtr, this, value);
  }

  public int getL1_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_L1_locatestate_get(swigCPtr, this);
  }

  public void setL5_kf_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_L5_kf_result_set(swigCPtr, this, value);
  }

  public double[] getL5_kf_result() {
    return IPSJNI.IndoorPositionMeasurement_L5_kf_result_get(swigCPtr, this);
  }

  public void setL5_kf_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_L5_kf_locatestate_set(swigCPtr, this, value);
  }

  public int getL5_kf_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_L5_kf_locatestate_get(swigCPtr, this);
  }

  public void setL1_kf_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_L1_kf_result_set(swigCPtr, this, value);
  }

  public double[] getL1_kf_result() {
    return IPSJNI.IndoorPositionMeasurement_L1_kf_result_get(swigCPtr, this);
  }

  public void setL1_kf_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_L1_kf_locatestate_set(swigCPtr, this, value);
  }

  public int getL1_kf_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_L1_kf_locatestate_get(swigCPtr, this);
  }

  public void setCarrier_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_carrier_result_set(swigCPtr, this, value);
  }

  public double[] getCarrier_result() {
    return IPSJNI.IndoorPositionMeasurement_carrier_result_get(swigCPtr, this);
  }

  public void setCarrier_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_carrier_locatestate_set(swigCPtr, this, value);
  }

  public int getCarrier_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_carrier_locatestate_get(swigCPtr, this);
  }

  public void setPse_exp_result(double[] value) {
    IPSJNI.IndoorPositionMeasurement_pse_exp_result_set(swigCPtr, this, value);
  }

  public double[] getPse_exp_result() {
    return IPSJNI.IndoorPositionMeasurement_pse_exp_result_get(swigCPtr, this);
  }

  public void setPse_exp_locatestate(int value) {
    IPSJNI.IndoorPositionMeasurement_pse_exp_locatestate_set(swigCPtr, this, value);
  }

  public int getPse_exp_locatestate() {
    return IPSJNI.IndoorPositionMeasurement_pse_exp_locatestate_get(swigCPtr, this);
  }

  public IndoorPositionMeasurement(double x, double y, double z, double t_f, boolean s, int inlocatestate) {
    this(IPSJNI.new_IndoorPositionMeasurement(x, y, z, t_f, s, inlocatestate), true);
  }

  public double getXAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getXAxisCoordinate(swigCPtr, this);
  }

  public double getYAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getYAxisCoordinate(swigCPtr, this);
  }

  public double getZAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getZAxisCoordinate(swigCPtr, this);
  }

  public int getlocatestate() {
    return IPSJNI.IndoorPositionMeasurement_getlocatestate(swigCPtr, this);
  }

  public void setDescription(String desc) {
    IPSJNI.IndoorPositionMeasurement_setDescription(swigCPtr, this, desc);
  }

  public void addDescription(String desc) {
    IPSJNI.IndoorPositionMeasurement_addDescription(swigCPtr, this, desc);
  }

  public String getDescription() {
    return IPSJNI.IndoorPositionMeasurement_getDescription(swigCPtr, this);
  }

  public boolean isSuccessful() {
    return IPSJNI.IndoorPositionMeasurement_isSuccessful(swigCPtr, this);
  }

}
