/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class IndoorPositionMeasurement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IndoorPositionMeasurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndoorPositionMeasurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_IndoorPositionMeasurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDescription(String desc) {
    IPSJNI.IndoorPositionMeasurement_setDescription(swigCPtr, this, desc);
  }

  public IndoorPositionMeasurement(double x, double y, double z, boolean s, int locatestate) {
    this(IPSJNI.new_IndoorPositionMeasurement(x, y, z, s, locatestate), true);
  }

  public double getXAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getXAxisCoordinate(swigCPtr, this);
  }

  public double getYAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getYAxisCoordinate(swigCPtr, this);
  }

  public double getZAxisCoordinate() {
    return IPSJNI.IndoorPositionMeasurement_getZAxisCoordinate(swigCPtr, this);
  }

  public int getlocatestate() {
    return IPSJNI.IndoorPositionMeasurement_getlocatestate(swigCPtr, this);
  }

  public String getDescription() {
    return IPSJNI.IndoorPositionMeasurement_getDescription(swigCPtr, this);
  }

  public boolean isSuccessful() {
    return IPSJNI.IndoorPositionMeasurement_isSuccessful(swigCPtr, this);
  }

}
