/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class Inputparameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Inputparameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Inputparameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_Inputparameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Inputparameter() {
    this(IPSJNI.new_Inputparameter__SWIG_0(), true);
  }

  public void setRoomCenter(double[] value) {
    IPSJNI.Inputparameter_roomCenter_set(swigCPtr, this, value);
  }

  public double[] getRoomCenter() {
    return IPSJNI.Inputparameter_roomCenter_get(swigCPtr, this);
  }

  public void setThreshold_x_y(double[] value) {
    IPSJNI.Inputparameter_threshold_x_y_set(swigCPtr, this, value);
  }

  public double[] getThreshold_x_y() {
    return IPSJNI.Inputparameter_threshold_x_y_get(swigCPtr, this);
  }

  public void setRef_Coord(double[] value) {
    IPSJNI.Inputparameter_ref_Coord_set(swigCPtr, this, value);
  }

  public double[] getRef_Coord() {
    return IPSJNI.Inputparameter_ref_Coord_get(swigCPtr, this);
  }

  public void setMocrator_fix_coord(double[] value) {
    IPSJNI.Inputparameter_mocrator_fix_coord_set(swigCPtr, this, value);
  }

  public double[] getMocrator_fix_coord() {
    return IPSJNI.Inputparameter_mocrator_fix_coord_get(swigCPtr, this);
  }

  public void setMocrator_deg(double value) {
    IPSJNI.Inputparameter_mocrator_deg_set(swigCPtr, this, value);
  }

  public double getMocrator_deg() {
    return IPSJNI.Inputparameter_mocrator_deg_get(swigCPtr, this);
  }

  public void setJingwei_deg(double value) {
    IPSJNI.Inputparameter_jingwei_deg_set(swigCPtr, this, value);
  }

  public double getJingwei_deg() {
    return IPSJNI.Inputparameter_jingwei_deg_get(swigCPtr, this);
  }

  public void setIs_L1_pse(boolean value) {
    IPSJNI.Inputparameter_is_L1_pse_set(swigCPtr, this, value);
  }

  public boolean getIs_L1_pse() {
    return IPSJNI.Inputparameter_is_L1_pse_get(swigCPtr, this);
  }

  public void setListL1(String value) {
    IPSJNI.Inputparameter_listL1_set(swigCPtr, this, value);
  }

  public String getListL1() {
    return IPSJNI.Inputparameter_listL1_get(swigCPtr, this);
  }

  public void setListL5(String value) {
    IPSJNI.Inputparameter_listL5_set(swigCPtr, this, value);
  }

  public String getListL5() {
    return IPSJNI.Inputparameter_listL5_get(swigCPtr, this);
  }

  public void set_roomCenter(double[] p) {
    IPSJNI.Inputparameter_set_roomCenter(swigCPtr, this, p);
  }

  public void set_threshold_x_y(double[] p) {
    IPSJNI.Inputparameter_set_threshold_x_y(swigCPtr, this, p);
  }

  public void set_refCoord(double[] p) {
    IPSJNI.Inputparameter_set_refCoord(swigCPtr, this, p);
  }

  public void set_mocrator_fix_coord(double[] p) {
    IPSJNI.Inputparameter_set_mocrator_fix_coord(swigCPtr, this, p);
  }

  public void set_mocrator_deg(double p) {
    IPSJNI.Inputparameter_set_mocrator_deg(swigCPtr, this, p);
  }

  public void set_jingwei_deg(double p) {
    IPSJNI.Inputparameter_set_jingwei_deg(swigCPtr, this, p);
  }

  public void set_is_L1_pse(boolean p) {
    IPSJNI.Inputparameter_set_is_L1_pse(swigCPtr, this, p);
  }

  public Inputparameter(double[] p_roomCenter, double[] p_threshold_x_y, double[] p_ref_Coord, double[] p_mocrator_fix_coord, double p_mocrator_deg, double p_jingwei_deg, boolean pis_L1_pse) {
    this(IPSJNI.new_Inputparameter__SWIG_1(p_roomCenter, p_threshold_x_y, p_ref_Coord, p_mocrator_fix_coord, p_mocrator_deg, p_jingwei_deg, pis_L1_pse), true);
  }

}
