/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class SatelliteIndoorMeasurement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected SatelliteIndoorMeasurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SatelliteIndoorMeasurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_SatelliteIndoorMeasurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SatelliteIndoorMeasurement setSvid(int s) {
    long cPtr = IPSJNI.SatelliteIndoorMeasurement_setSvid(swigCPtr, this, s);
    return (cPtr == 0) ? null : new SatelliteIndoorMeasurement(cPtr, true);
  }

  public int getSvid() {
    return IPSJNI.SatelliteIndoorMeasurement_getSvid(swigCPtr, this);
  }

  public SatelliteIndoorMeasurement setPseudorange(double p) {
    long cPtr = IPSJNI.SatelliteIndoorMeasurement_setPseudorange(swigCPtr, this, p);
    return (cPtr == 0) ? null : new SatelliteIndoorMeasurement(cPtr, true);
  }

  public double getPseudorange() {
    return IPSJNI.SatelliteIndoorMeasurement_getPseudorange(swigCPtr, this);
  }

  public double getcn0DbHz() {
    return IPSJNI.SatelliteIndoorMeasurement_getcn0DbHz(swigCPtr, this);
  }

  public double getpseudorangeRateMetersPerSecond() {
    return IPSJNI.SatelliteIndoorMeasurement_getpseudorangeRateMetersPerSecond(swigCPtr, this);
  }

  public void setpseudorangeRateMetersPerSecond(double p) {
    IPSJNI.SatelliteIndoorMeasurement_setpseudorangeRateMetersPerSecond(swigCPtr, this, p);
  }

  public double getaccumulatedDeltaRangeMeters() {
    return IPSJNI.SatelliteIndoorMeasurement_getaccumulatedDeltaRangeMeters(swigCPtr, this);
  }

  public void setaccumulatedDeltaRangeMeters(double p) {
    IPSJNI.SatelliteIndoorMeasurement_setaccumulatedDeltaRangeMeters(swigCPtr, this, p);
  }

  public float getcarrierFrequencyHz() {
    return IPSJNI.SatelliteIndoorMeasurement_getcarrierFrequencyHz(swigCPtr, this);
  }

  public void setcarrierFrequencyHz(float p) {
    IPSJNI.SatelliteIndoorMeasurement_setcarrierFrequencyHz(swigCPtr, this, p);
  }

  public int getaccumulatedDeltaRangeState() {
    return IPSJNI.SatelliteIndoorMeasurement_getaccumulatedDeltaRangeState(swigCPtr, this);
  }

  public void setaccumulatedDeltaRangeState(int p) {
    IPSJNI.SatelliteIndoorMeasurement_setaccumulatedDeltaRangeState(swigCPtr, this, p);
  }

  public double getreceivedSvTimeUncertaintyNanos() {
    return IPSJNI.SatelliteIndoorMeasurement_getreceivedSvTimeUncertaintyNanos(swigCPtr, this);
  }

  public void setreceivedSvTimeUncertaintyNanos(double p) {
    IPSJNI.SatelliteIndoorMeasurement_setreceivedSvTimeUncertaintyNanos(swigCPtr, this, p);
  }

  public double getpseudorangeRateUncertaintyMetersPerSecond() {
    return IPSJNI.SatelliteIndoorMeasurement_getpseudorangeRateUncertaintyMetersPerSecond(swigCPtr, this);
  }

  public void setpseudorangeRateUncertaintyMetersPerSecond(double p) {
    IPSJNI.SatelliteIndoorMeasurement_setpseudorangeRateUncertaintyMetersPerSecond(swigCPtr, this, p);
  }

  public double getaccumulatedDeltaRangeUncertaintyMeters() {
    return IPSJNI.SatelliteIndoorMeasurement_getaccumulatedDeltaRangeUncertaintyMeters(swigCPtr, this);
  }

  public void setaccumulatedDeltaRangeUncertaintyMeters(double p) {
    IPSJNI.SatelliteIndoorMeasurement_setaccumulatedDeltaRangeUncertaintyMeters(swigCPtr, this, p);
  }

  public SatelliteIndoorMeasurement() {
    this(IPSJNI.new_SatelliteIndoorMeasurement(), true);
  }

}
