/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class SatelliteIndoorMeasurementList extends java.util.AbstractList<SatelliteIndoorMeasurement> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SatelliteIndoorMeasurementList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SatelliteIndoorMeasurementList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_SatelliteIndoorMeasurementList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SatelliteIndoorMeasurementList(SatelliteIndoorMeasurement[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SatelliteIndoorMeasurement element : initialElements) {
      add(element);
    }
  }

  public SatelliteIndoorMeasurementList(Iterable<SatelliteIndoorMeasurement> initialElements) {
    this();
    for (SatelliteIndoorMeasurement element : initialElements) {
      add(element);
    }
  }

  public SatelliteIndoorMeasurement get(int index) {
    return doGet(index);
  }

  public SatelliteIndoorMeasurement set(int index, SatelliteIndoorMeasurement e) {
    return doSet(index, e);
  }

  public boolean add(SatelliteIndoorMeasurement e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SatelliteIndoorMeasurement e) {
    modCount++;
    doAdd(index, e);
  }

  public SatelliteIndoorMeasurement remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SatelliteIndoorMeasurementList() {
    this(IPSJNI.new_SatelliteIndoorMeasurementList__SWIG_0(), true);
  }

  public SatelliteIndoorMeasurementList(SatelliteIndoorMeasurementList other) {
    this(IPSJNI.new_SatelliteIndoorMeasurementList__SWIG_1(SatelliteIndoorMeasurementList.getCPtr(other), other), true);
  }

  public long capacity() {
    return IPSJNI.SatelliteIndoorMeasurementList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    IPSJNI.SatelliteIndoorMeasurementList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return IPSJNI.SatelliteIndoorMeasurementList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IPSJNI.SatelliteIndoorMeasurementList_clear(swigCPtr, this);
  }

  public SatelliteIndoorMeasurementList(int count, SatelliteIndoorMeasurement value) {
    this(IPSJNI.new_SatelliteIndoorMeasurementList__SWIG_2(count, SatelliteIndoorMeasurement.getCPtr(value), value), true);
  }

  private int doSize() {
    return IPSJNI.SatelliteIndoorMeasurementList_doSize(swigCPtr, this);
  }

  private void doAdd(SatelliteIndoorMeasurement x) {
    IPSJNI.SatelliteIndoorMeasurementList_doAdd__SWIG_0(swigCPtr, this, SatelliteIndoorMeasurement.getCPtr(x), x);
  }

  private void doAdd(int index, SatelliteIndoorMeasurement x) {
    IPSJNI.SatelliteIndoorMeasurementList_doAdd__SWIG_1(swigCPtr, this, index, SatelliteIndoorMeasurement.getCPtr(x), x);
  }

  private SatelliteIndoorMeasurement doRemove(int index) {
    return new SatelliteIndoorMeasurement(IPSJNI.SatelliteIndoorMeasurementList_doRemove(swigCPtr, this, index), true);
  }

  private SatelliteIndoorMeasurement doGet(int index) {
    return new SatelliteIndoorMeasurement(IPSJNI.SatelliteIndoorMeasurementList_doGet(swigCPtr, this, index), true);
  }

  private SatelliteIndoorMeasurement doSet(int index, SatelliteIndoorMeasurement val) {
    return new SatelliteIndoorMeasurement(IPSJNI.SatelliteIndoorMeasurementList_doSet(swigCPtr, this, index, SatelliteIndoorMeasurement.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    IPSJNI.SatelliteIndoorMeasurementList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
