/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.indoor.position.swiggenerated;

public class SatelliteInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SatelliteInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SatelliteInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IPSJNI.delete_SatelliteInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SatelliteInfo(double x, double y, double z, int svid) {
    this(IPSJNI.new_SatelliteInfo(x, y, z, svid), true);
  }

  public double getXAxisCoordinate() {
    return IPSJNI.SatelliteInfo_getXAxisCoordinate(swigCPtr, this);
  }

  public double getYAxisCoordinate() {
    return IPSJNI.SatelliteInfo_getYAxisCoordinate(swigCPtr, this);
  }

  public double getZAxisCoordinate() {
    return IPSJNI.SatelliteInfo_getZAxisCoordinate(swigCPtr, this);
  }

  public int getSvid() {
    return IPSJNI.SatelliteInfo_getSvid(swigCPtr, this);
  }

}
